version: '3'

services:
  devcontainer:
    image: ghcr.io/getwarp/warp-php-devcontainer:8.1
    command: [ 'sleep', 'infinite' ]
    environment:
      # See https://xdebug.org/docs/all_settings for more
      XDEBUG_CONFIG: 'idekey=warp client_host=host.docker.internal'
      XDEBUG_MODE: 'debug'
    volumes:
      - ./:/home/warp/app
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
